In [1]:
import pandas as pd
import numpy as np


poke = pd.read_csv("./datasets/pokemon_data.csv")

In [2]:
poke[-5:]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
# Get gen 6 pokemons

poke[poke.Generation == 6]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [4]:
poke[(poke.Legendary) & (poke['Type 1'] == "Fire")]['Name']

158      Moltres
263        Entei
270        Ho-oh
542      Heatran
799    Volcanion
Name: Name, dtype: object

In [5]:
# Finding specific element by text

poke.loc[poke['Type 1'] == "Ice"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
133,124,Jynx,Ice,Psychic,65,50,35,115,95,95,1,False
156,144,Articuno,Ice,Flying,90,85,100,95,125,85,1,True
238,220,Swinub,Ice,Ground,50,50,40,30,30,50,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
243,225,Delibird,Ice,Flying,45,55,45,65,45,75,2,False
257,238,Smoochum,Ice,Psychic,45,30,15,85,65,65,2,False
395,361,Snorunt,Ice,NaN,50,50,50,50,50,50,3,False
396,362,Glalie,Ice,NaN,80,80,80,80,80,80,3,False
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False
398,363,Spheal,Ice,Water,70,40,50,55,50,25,3,False
399,364,Sealeo,Ice,Water,90,60,70,75,70,45,3,False
400,365,Walrein,Ice,Water,110,80,90,95,90,65,3,False
415,378,Regice,Ice,NaN,80,50,100,100,200,50,3,True
522,471,Glaceon,Ice,NaN,65,60,110,130,95,65,4,False
524,473,Mamoswine,Ice,Ground,110,130,80,70,60,80,4,False
530,478,Froslass,Ice,Ghost,70,80,70,80,70,110,4,False
643,582,Vanillite,Ice,NaN,36,50,50,65,60,44,5,False
644,583,Vanillish,Ice,NaN,51,65,65,80,75,59,5,False
645,584,Vanilluxe,Ice,NaN,71,95,85,110,95,79,5,False
674,613,Cubchoo,Ice,NaN,55,70,40,60,40,40,5,False
675,614,Beartic,Ice,NaN,95,110,80,70,80,50,5,False
676,615,Cryogonal,Ice,NaN,70,50,30,95,135,105,5,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False

In [6]:
# Sorting

poke.sort_values(['Attack', 'HP'], ascending=True)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True

In [7]:
# Making Changes to the data

# Add Total
poke['Total'] = np.sum(poke.iloc[:, 4:10], axis=1)

poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [8]:
# Saving csv

poke.to_csv("./datasets/modified.csv")


# No index
poke.to_csv("./datasets/modified.csv", index=False)


poke[:10]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False,314

In [9]:
# Filtering Data

# poke[poke['Type 1'] == 'Fire'].iloc[3]

# poke.loc[poke['Name'].str.isnumeric]

# poke['Type 1'].str.contains('fire', regex=True, case=False)
poke

0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Name, Length: 800, dtype: bool

In [49]:
# Conditional Changes

# poke.loc[poke['Type 1'].str.contains('Flame'), 'Type 1'] = 'Fire'

poke.loc[:, 'Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [74]:
# Aggregate Stats
poke = pd.read_csv('./datasets/modified.csv')


pokearr = poke.drop(columns=['Name', 'Type 2', 'Legendary', 'Generation'])
# pokearr
pokearr.groupby(['Type 1']).count().sort_values('#', ascending=False)['']

            #   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total
Type 1
Water     112  112     112      112      112      112    112    112
Normal     98   98      98       98       98       98     98     98
Grass      70   70      70       70       70       70     70     70
Bug        69   69      69       69       69       69     69     69
Psychic    57   57      57       57       57       57     57     57
Fire       52   52      52       52       52       52     52     52
Electric   44   44      44       44       44       44     44     44
Rock       44   44      44       44       44       44     44     44
Ground     32   32      32       32       32       32     32     32
Dragon     32   32      32       32       32       32     32     32
Ghost      32   32      32       32       32       32     32     32
Dark       31   31      31       31       31       31     31     31
Poison     28   28      28       28       28       28     28     28
Fighting   27   27      27       27       27       27     27     27
Steel      27   27      27       27       27       27     27     27
Ice        24   24      24       24       24       24     24     24
Fairy      17   17      17       17       17       17     17     17
Flying      4    4       4        4        4        4      4      4